name: Node.js CI
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install --global npm
      - run: npm ci
      - run: npm run-script build
      - run: npm test
    strategy:
      matrix:
        node-version:
          - 12
          - 14
          - 16
  lhci:
    permissions:
      statuses: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          cache: npm
      - run: npm ci
      - run: npm run-script build
      - run: npm exec -- lhci autorun
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.event.pull_request.head.sha }}
          LHCI_GITHUB_TOKEN: ${{ github.token }}
  deploy:
    needs: lhci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          cache: npm
      - run: npm ci
      - run: npm run-script build
      - run: git switch --orphan gh-pages
      - run: git add .
      - run: git config user.name .github/workflows/node.js.yml
      - run: git config user.email github-actions@github.com
      - run: |
          git diff --quiet --cached ||
          git commit \
            --message "🚀 Deploy $GITHUB_SHA" \
            --message "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
      - run: git push --force origin gh-pages
